language: java
jdk:
  - oraclejdk8
  - oraclejdk11
  - oraclejdk15

sudo: false

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - jackmoloko@yandex.ru
    on_success: never
    on_failure: always